### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by haleyjd** [aqrit/ddwrapper#1]
Hello,

I am a private contractor for a company that focuses on revival of retro games and it just happens that your ddwrapper project seems to resolve all the issues with a game we would like to put back on the market. There is no license included with the component stating whether or not distribution with a commercial product is allowed, so I was hoping to get a statement on this from you, as we want to do the most possible to respect others' rights.

**Comment by aqrit** [comment]
For commercial use:
Send an email to mike@bitpatch.com containing the title of the game and the name of the distributor(s).  ddwrapper can then be used, studied, modified and redistributed freely.

Note: the code on github is an improved version of the wrapper but it contains no "fixes".
So the same license terms also apply to the http://www.bitpatch.com/ddwrapper.html code base.

---

If anyone ever wants to throw work my way...
I've patched dozens of old games and I'm fairly handy with a disassembler. ;-)
